GuardingUS/Controllers/AddressController.cs
using GuardingUS.Models;
using GuardingUS.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace GuardingUS.Controllers
{
    [Authorize(Roles = Constants.RoleAdmin)]
    public class AddressController : Controller
    {
        private readonly IAddressRepository addressRepository;

        public AddressController(IAddressRepository addressRepository)
        {
            this.addressRepository = addressRepository;
        }
        public async Task<IActionResult> Index()
        {
            var address = await addressRepository.Get();
            return View(address);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Address address)
        {
            if (!ModelState.IsValid)
            {
                return View(address);
            }

            await addressRepository.Create(address);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string id)
        {
            var address = await addressRepository.GetById(id);
            return View(address);
        }

        [HttpPost]
        public async Task<IActionResult> Update(Address editAddress)
        {
            await addressRepository.Update(editAddress);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string id)
        {
            var address = await addressRepository.GetById(id);
            return View(address);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteAddress(string id)
        {
            await addressRepository.Delete(id);
            return RedirectToAction("Index");
        }
    }
}

GuardingUS/Controllers/HomesController.cs
using AutoMapper;
using GuardingUS.Models;
using GuardingUS.Models.ViewModels;
using GuardingUS.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using System.Security.Claims;

namespace GuardingUS.Controllers
{
    [Authorize(Roles = Constants.RoleAdmin)]
    public class HomesController : Controller
    {
        private readonly IHomeRepository homeRepository;
        private readonly IAddressRepository addressRepository;
        private readonly IMapper mapper;
        private readonly IUserRepository userRepository;
        private readonly IUserService userService;

        public HomesController(IHomeRepository homeRepository, IAddressRepository addressRepository, IMapper mapper, IUserRepository userRepository, IUserService userService)
        {
            this.homeRepository = homeRepository;
            this.addressRepository = addressRepository;
            this.mapper = mapper;
            this.userRepository = userRepository;
            this.userService = userService;
        }
        public async Task<IActionResult> Index()
        {
            var homes = await homeRepository.Get();
            return View(homes);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new AddHomeVM();
            model.Address = await GetAddress();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddHomeVM home)
        {
            await homeRepository.Create(home);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(string id)
        {
            var home = await homeRepository.GetById(id);

            //var model = mapper.Map<AddHomeVM>(home);

            var model = new AddHomeVM()
            {
                Id = home.Id,
                Number = home.Number,
                Cars = home.Cars,
                IdAddress = home.IdAddress,
                IdUser = home.IdUser

            };

            model.Address = await GetAddress();
            model.Owners = await GetUsers();

            return View(model);

        }

        [HttpPost]
        public async Task<IActionResult> Update(AddHomeVM homeEdit)
        {
            await homeRepository.Update(homeEdit);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(string id)
        {
            var home = await homeRepository.GetById(id);
            return View(home);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteHome(string id)
        {
            await homeRepository.Delete(id);
            return RedirectToAction("Index");
        }



        private async Task<IEnumerable<SelectListItem>> GetAddress()
        {
            var accountsTypes = await addressRepository.Get();

            return accountsTypes.Select(x => new SelectListItem(x.Name, x.Id));

        }

        private async Task<IEnumerable<SelectListItem>> GetUsers()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            //var userId = userService.GetUserId();
            var users = await userRepository.Get(userId);

            //return users.Select(x => new SelectListItem(x.UserName, x.Id.ToString()));
            return users.Select(x => new SelectListItem(x.UserName, x.Id));
        }




    }
}

GuardingUS/Controllers/NotificationsController.cs
using GuardingUS.Models;
using GuardingUS.Models.ViewModels;
using GuardingUS.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Data;
using System.Diagnostics;
using System.Security.Claims;

namespace GuardingUS.Controllers
{
    public class NotificationsController : Controller
    {
        private readonly INotificationRepository notificationRepository;
        private readonly IUserService userService;
        private readonly IUserRepository userRepository;

        public NotificationsController(INotificationRepository notificationRepository, IUserService userService, IUserRepository userRepository)
        {
            this.notificationRepository = notificationRepository;
            this.userService = userService;
            this.userRepository = userRepository;
        }
        
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            //var userId = userService.GetUserId();
            var notifications = await notificationRepository.Get(userId);
            return View(notifications);
        }

        public async Task<IActionResult> Message(string id)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            //var userId = userService.GetUserId();
            var message = await notificationRepository.Get(id,userId);
            return View(message);
        }

        [HttpGet]
        public async Task<IActionResult> SendIndividual()
        {
            var model = new AddNotificationVM();
            model.Users = await GetUsers();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(AddNotificationVM notification)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            //var userId = userService.GetUserId();
            var receiveId = notification.IdUser;
            notification.IdUser = userId;
            await notificationRepository.Create(notification);

            var model = new UserNotifications();
            model.IdUser = receiveId;
            model.IdNotification = notification.Id;

            await notificationRepository.Send(model);
            

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> SendGroup()
        {
            var model = new AddNotificationVM();
            model.Users = await GetRoles();


            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CreateGroup(AddNotificationVM notification)
        {
            //Create Notification
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            //var userId = userService.GetUserId();
            var receiveId = notification.IdUser;
            notification.IdUser = userId;
            await notificationRepository.Create(notification);

            //Send Notification
       
            IEnumerable<SelectList> myid = await GetUserList(receiveId);
            foreach (var item in myid)
            {
                var model = new UserNotifications();
                model.IdUser = item.Items.ToString();
                model.IdNotification = notification.Id;

                await notificationRepository.Send(model);
            }


            return RedirectToAction("Index");
        }


        private async Task<IEnumerable<SelectListItem>> GetUsers()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            //var userId = userService.GetUserId();
            var users = await userRepository.Get(userId);
            return users.Select(x => new SelectListItem(x.UserName, x.Id));
        }

        private async Task<IEnumerable<SelectListItem>> GetRoles()
        {

            var users = await notificationRepository.GetGroup();
            return users.Select(x => new SelectListItem(x.Name, x.Id)); 
        }

        private async Task<IEnumerable<SelectList>> GetUserList(string id)
        {
            var userList = await notificationRepository.GetUsers(id);
            return userList.Select(x => new SelectList(x.UserId));
            
        }




    }
}

GuardingUS/Controllers/UsersController.cs
using AutoMapper;
using GuardingUS.Models;
using GuardingUS.Models.ViewModels;
using GuardingUS.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;

namespace GuardingUS.Controllers
{
    public class UsersController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly IUserRepository userRepository;
        private readonly IMapper mapper;
        private readonly IRoleRepository roleRepository;
        private readonly IUserService userService;
        private readonly ApplicationDbContext context;

        public UsersController(UserManager<IdentityUser> userManager, SignInManager<IdentityUser> signInManager, IUserRepository userRepository, IMapper mapper, IRoleRepository roleRepository, IUserService userService, ApplicationDbContext context)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.userRepository = userRepository;
            this.mapper = mapper;
            this.roleRepository = roleRepository;
            this.userService = userService;
            this.context = context;
        }

        [Authorize(Roles = Constants.RoleAdmin)]
        public async Task<IActionResult> Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            //var userId = userService.GetUserId();
            var users = await userRepository.Get(userId);
            
            return View(users);
        }

        [AllowAnonymous]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Register(RegisterVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            //var user = new Users() { Name = model.Name,Email = model.Email, PhoneNumber = model.PhoneNumber };
            var user = new IdentityUser() { Email = model.Email, PhoneNumber = model.PhoneNumber, UserName = model.UserName };


            var result = await userManager.CreateAsync(user, password: model.Password);

            if (result.Succeeded)
            {
                await signInManager.SignInAsync(user, isPersistent: true);
                return RedirectToAction("Index", "Visitors");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                return View(model);
            }

        }

        [HttpGet]
        [AllowAnonymous]
        public IActionResult Login()
        {

            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(LoginVM model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var result = await signInManager.PasswordSignInAsync(model.UserName,
                model.Password, model.RememberMe, lockoutOnFailure: false);

            if (result.Succeeded)
            {
                return RedirectToAction("Index", "Visitors");
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Name of the user or password is incorrect");
                return View(model);
            }
        }


        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(IdentityConstants.ApplicationScheme);
            return RedirectToAction("Index", "Visitors");
        }

        [Authorize(Roles = Constants.RoleAdmin)]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await userRepository.GetById(id);
            user.RoleId = await userRepository.GetRoleId(id);

            var model = mapper.Map<EditUserVM>(user);

            model.Roles = await GetRoles();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Update(EditUserVM userEdit)
        {

            //await userRepository.Update(userEdit);
            var usuario = await context.Users.Where(u => u.Id == userEdit.Id).FirstOrDefaultAsync();

            if (userEdit.RoleId == "9A0258A5-D55B-40D8-B67C-F4634B40959E")
            {
                await userManager.AddToRoleAsync(usuario, Constants.RoleAdmin);
            }
            else if (userEdit.RoleId == "A1488B44-508C-4740-B444-87460139EBB7")
            {
                await userManager.AddToRoleAsync(usuario, Constants.RoleGuard);
            }
            else {
                await userManager.AddToRoleAsync(usuario, Constants.RoleResident);
            }
            

            //await userRepository.Update(userEdit);

            return RedirectToAction("Index");

        }
        [Authorize(Roles = Constants.RoleAdmin)]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await userRepository.GetById(id);
            user.UserId = user.Id;
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteUser(string id)
        {
            //HW Crear un metodo para editar el owner de la casa y en cambiar el user de las notificaciones
            var userid = id;

            //var user = await context.Users.Where(u => u.Id == userid).FirstOrDefaultAsync();
            //await userManager.SetLockoutEnabledAsync(user, true);
            //await userManager.SetLockoutEndDateAsync(user,DateTime.Today.AddYears(10));

            await userRepository.UpdateUnknown(userid);
            await userRepository.Delete(userid,id);
            return RedirectToAction("Index");
        }

        private async Task<IEnumerable<SelectListItem>> GetRoles()
        {
            var accountsTypes = await roleRepository.Get();

            return accountsTypes.Select(x => new SelectListItem(x.Name, x.Id));

        }


    }
}

GuardingUS/Views/Shared/_Layout.cshtml
@using GuardingUS.Services;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GuardingUS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GuardingUS.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GuardingUS</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (User.IsInRole(Constants.RoleAdmin)){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visitors" asp-action="Index">Visitors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Index">Users</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Address" asp-action="Index">Address</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Homes" asp-action="Index">Homes</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                        </li>
                        }
                        @if (User.IsInRole(Constants.RoleGuard)){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Visitors" asp-action="Index">Visitors</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                        </li>
                        }
                        @if (User.IsInRole(Constants.RoleResident)){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Notifications" asp-action="Index">Notifications</a>
                        </li>
                        }
                    </ul>
                    <partial name="_LinksLogin" />  
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - GuardingUS - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
@*    <script src="~/lib/jquery-ui/jquery-ui.min.js" ></script>
*@    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GuardingUS/Views/Shared/_LinksLogin.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager


<ul class="navbar-nav">
    @if (SignInManager.IsSignedIn(User))
    {
        <li class="nav-item">
            <span class="nav-link-danger text-dark">Hola, @User.Identity.Name</span>
        </li>
        <li>
            <form class="form-inline" asp-action="Logout" asp-controller="Users">
                <button type="submit" class="nav-link btn btn-link text-dark">
                    Logout
                </button>
            </form>
        </li>
    }
    else
    {
            <li class="nav-item">
                <a class="nav-link dark-text" asp-controller="Users" asp-action="Register">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link dark-text" asp-controller="Users" asp-action="Login">Login</a>
            </li>
    }
 </ul>